# time: 时间与 duration 类型
# 期望输出:
#   before
#   after
#   t0 < t1: true
#   t0 > t1: false
#   delta >= 0 ns: true
#   delta ms >= 0: true
#   delta s >= 0: true
#   t0 + delta == t1: true
#   1000 ms
#   1 s = 1000000000 ns
rwfunc main() -> () {
    println("before")
    t0 <- time.now()
    println("after")
    t1 <- time.now()

    before <- time.before(t0, t1)
    print("t0 < t1: ")
    println(before)

    after <- time.after(t0, t1)
    print("t0 > t1: ")
    println(after)

    delta <- time.sub(t1, t0)
    print("delta >= 0 ns: ")
    zero = time.duration.nanos(0)  # = 等价于 <-
    println(time.duration.before(zero, delta))

    ms <- time.duration.as_millis(delta)
    print("delta ms >= 0: ")
    println(ms >= 0)

    s <- time.duration.as_seconds(delta)
    print("delta s >= 0: ")
    println(s >= 0)

    sum <- time.add(t0, delta)
    print("t0 + delta == t1: ")
    a <- not(time.before(sum, t1))
    b <- not(time.after(sum, t1))
    println(and(a, b))

    1000 -> n  # = 等价于 <-
    print(n)
    println(" ms")

    one_sec <- time.duration.seconds(1)
    ns <- time.duration.as_nanos(one_sec)
    print("1 s = ")
    print(ns)
    println(" ns")
}
main()
