name: ci
on: [push, pull_request, repository_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test-${{ matrix.backend.name }}
    strategy:
      fail-fast: false
      matrix:
        backend:
          - { name: shm, dsn: "shm:///tmp/kvlang_ci_shm.shm" }
          - { name: fs,  dsn: "fs:///tmp/kvlang_ci_fs" }
    steps:
      - uses: actions/checkout@v4
      - name: 下载 ABI 依赖
        env: { GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
        run: ./ci/deps.sh
      - name: 构建
        run: |
          make runtime
          make layout
          sudo cp layout/target/release/libkvlanglayout.so /usr/lib/
          make runtime-rs
          sudo make install
      - name: 测试 (${{ matrix.backend.name }})
        env: { KVSPACE: "${{ matrix.backend.dsn }}", KV_CASE_TIMEOUT: "600" }
        run: python3 tutorial/test.py
